### ISSUE TITLE
Image integration ?

### ISSUE THREAD

**Issue by Depado** [matcornic/hermes#12]
Hey there !
First of all thanks for the awesome project 😃 

I'm wondering if there's a clean way of inserting an image in the generated mail ?
It's possible to use the `FreeMarkdown` field (using the `![...](https://...)` notation), but I don't know if it's currently possible to insert pictures without that technique.

**Comment by Depado** [comment]
Would that be a bad thing if I replaced the `[]string` with `[]template.HTML` instead ? Could it cause unexpected behavior ? Just wondering.

**Comment by matcornic** [comment]
Intros and Outros are meant to be sentences, not HTML content. The email templates follow patterns for clean emails. It's not meant to be used with image, just simple buttons. 

If you need more custom content, use `FreeMarkdown` field.

Note: you could change `[]string` to `[]template.HTML`, but don't forget it means you accept any HTML content

**Comment by Depado** [comment]
Hi,
Yes that's what I did because I needed to add links in Intros and Outros. As I don't generate mails from user content it's fine for now. Thanks for your answer ☺
