### ISSUE TITLE
Modify the header and footer background in the flat theme

### ISSUE THREAD

**Issue by Mokto** [matcornic/hermes#13]
Hi,

Thanks for your work on this plugin.
I would like to be able to change the background of the header and the footer in the flat theme (or event the default theme).

I don't think there is a way to do this ?

Thanks.

**Comment by matcornic** [comment]
If you need to make a change in the theme, just copy the given golang theme file (e.g. `flat.go`) file in your Golang project and follow [these instructions](https://github.com/matcornic/hermes/blob/master/CONTRIBUTING.md#using-a-custom-theme)
