### ISSUE TITLE
Feature Request: FreeHTML option

### ISSUE THREAD

**Issue by issmirnov** [matcornic/hermes#26]
Hi,

Thanks for a great project - loving the ui and clean interface! I have a question and a potential feature request.

I'm working on a project that generates moderately complex html, and I'm trying to have this in the email. Would you be open to adding an`FreeMarkdown` analogue such as `FreeHTML`? I've been playing with casting and subclassing `hermes.Markdown` but not seeing any success.

Essentially I'm trying to get my html template data injected.

Thanks!

**Comment by matcornic** [comment]
Did you try to write HTML in `FreeMarkdown` ? HTML is supported in Markdown.

If you need to write plain HTML email from a template, I'm not sure this library fits your needs. Feel free to inspire yourself from HTML templates from `flat.go` or `default.go` (The templates are [Open Source themselves](https://github.com/matcornic/hermes#supported-themes)). You just need this kind of piece of code afterwards (Golang templating), extracted from `hermes.go`:

```go
// Generate the email from Golang template
// Allow usage of simple function from sprig : https://github.com/Masterminds/sprig
t, err := template.New("hermes").Funcs(sprig.FuncMap()).Funcs(templateFuncs).Parse(tplt)
if err != nil {
	return "", err
}
var b bytes.Buffer
t.Execute(&b, Template{*h, email})
return b.String(), nil
```

**Comment by issmirnov** [comment]
I have a function that returns a string with my HTML. I tried throwing that in directly `FreeMarkdown: generateHtml(),`, but I'm unable to cast the string to `hermes.Markdown`. I'm enjoying the rest of this library so if I could get that HTML in that's all that I need. Appreciate the pointers to the templates though!

Do you have any suggestions about casting and type conversions?

**Comment by issmirnov** [comment]
Hey, I ended up doing some pretty heavy modifications to the logic so as per your suggestion took flat.go and ran with it.

Thanks for the pointers!
