### ISSUE TITLE
MarkdownCommon is undefined

### ISSUE THREAD

**Issue by zloyded** [matcornic/hermes#27]
some thing wrong with deps```../vendor/github.com/matcornic/hermes/hermes.go:76:23: undefined: blackfriday.MarkdownCommon```

**Comment by matcornic** [comment]
Thank you for reporting this. 

Deps are vendored with `godep`, so it needs versions defined in https://github.com/matcornic/hermes/blob/master/Gopkg.lock

I'll look into it and update dependencies.

**Comment by matcornic** [comment]
I updated the dependencies (blackfriday as well). You should not have this problem anymore #28
