### ISSUE TITLE
undefined: blackfriday.Run

### ISSUE THREAD

**Issue by AlexDunmow** [matcornic/hermes#33]
New install: 

vendor/github.com/matcornic/hermes/hermes.go:76:23: undefined: blackfriday.Run

Seems blackfriday API has changed: 

```
// ToHTML converts Markdown to HTML
    func (c Markdown) ToHTML() template.HTML {
            return template.HTML(blackfriday.Run([]byte(string(c))))
    }
```

**Comment by matcornic** [comment]
Which Hermes version do you use (tag or git hash) ?

**Comment by nikooo777** [comment]
is this related? 

```
# ./app/vendor/github.com/matcornic/hermes
vendor/github.com/matcornic/hermes/hermes.go:76:23: undefined: blackfriday.MarkdownCommon
(error exit: exit status 2)
```

**Comment by xdefrag** [comment]
Find out that vgo for some reason installs v1.1.0 version default and build fails with this error. Vgo can't find v1.1.1, but pointing to specific commit or master branch solves a problem.

**Comment by matcornic** [comment]
@xdefrag probably because I mixed formats in the tag names. I renamed the 1.1.1 tag to v1.1.1

Could you try again ?

**Comment by xdefrag** [comment]
@matcornic Yep, it's worked. Thanks.
