### ISSUE TITLE
The ability to send attachments

### ISSUE THREAD

**Issue by jfonseca8** [matcornic/hermes#37]
Do you think it would be a good idea to be able to send attachments?

**Comment by matcornic** [comment]
Hermes is just a library for writing the body of the email, and won't be more than that. It does not handle sending the email.

There are other great libraries that are able to handle attachments though: see [gomail](https://github.com/go-gomail/gomail).
In gomail, the function [Attach](https://godoc.org/gopkg.in/gomail.v2#Message.Attach) is used for sending attachments.

Personally, I use gomail combined with Hermes. You can do something like this:

```go
	m := gomail.NewMessage()
	m.SetHeader("From", "test@test.com")
	m.SetHeader("To", "dest@test.com;other@test.com")
	m.SetHeader("Subject", "A subject of the email")
        m.Attach("/home/myuser/your_file_to_attach.pdf")

	emailBodyHTML, err := hermesConfig.GenerateHTML(options.Body)
	if err != nil {
		return err
	}

	// Generate the plaintext version of the e-mail (for clients that do not support xHTML)
	emailBodyPlainText, err := hermesConfig.GeneratePlainText(options.Body)
	if err != nil {
		return err
	}

	m.SetBody("text/plain", emailBodyPlainText)
	m.AddAlternative("text/html", emailBodyHTML)
       d := gomail.NewDialer(smtpConfig.Server, smtpConfig.Port, smtpConfig.SMTPUser, smtpConfig.SMTPPassword)

	d.DialAndSend(m)
```
