### ISSUE TITLE
When I try to install 1.2 version it returns an error

### ISSUE THREAD

**Issue by AkezhanOb1** [matcornic/hermes#47]
> go get -u github.com/matcornic/hermes

`../github.com/matcornic/hermes/hermes.go:8:2: cannot find package "github.com/russross/blackfriday/v2" in any of:
/usr/local/go/src/github.com/russross/blackfriday/v2 (from $GOROOT)
/go/src/github.com/russross/blackfriday/v2 (from $GOPATH)`

**Comment by matcornic** [comment]
Hello @akamensky, 

With `go get`, you will download latest version from master (so it's a 2.0).

Do you use go modules ? 
- If yes, use 2.0 and follow current README.
- If not, use old 1.2.0 version (which uses Go Dep for dependency management)
    - Are your dependencies managed by a dependency manager like Dep or govendor ?
       - If yes, you have to set the version of Hermes to v1.2.0 in your configuration file.
       - If not (you would use your Gopath only), you have to [checkout the tag](https://pinkstone.co.uk/how-to-checkout-a-previous-tag-in-git/) version of Hermes

I strongly encourage you to use go modules or any other dependency manager

Have a nice day

**Comment by arxdsilva** [comment]
Im having the same problem, with go `1.11.2` while installing

**Comment by crazy-max** [comment]
Same issue here with go `1.11.5`

**Comment by arxdsilva** [comment]
@crazy-max my branch https://github.com/arxdsilva/hermes/ fixes it

**Comment by crazy-max** [comment]
@arxdsilva Yeah indeed, I have `+1` your PR

**Comment by crazy-max** [comment]
A workaround is explained in russross/blackfriday#491
