### ISSUE TITLE
CID Embedded Images 

### ISSUE THREAD

**Issue by TudorHulban** [matcornic/hermes#54]
hi,
is it possible to use the library with content - id images and refer them in the HTML?
i understood the library targets more buttons, but for different client campaigns i should not be having the logo images in an external server, therefore the images need to be sent with the email .

thank you

**Comment by matcornic** [comment]
Hello @TudorHulban , you can put a base64 image as a string for `logo` property inside `hermes.Product`

Example:

```go
// Some tools exist to convert your image to base64
const logo = "data:image/png;base64,iVBORw0KGgoAAAAXXX[...]"
hermesConfig = hermes.Hermes{
  Theme: new(hermes.Flat),
  Product: hermes.Product{
    Name:      "MyProduct",
    Logo:      logo,
    Copyright: "Copyright © 2019 MyProduct. All rights reserved.",
  },
}
```

**Comment by pyros2097** [comment]
@matcornic truly you are slow to respond 🤣

**Comment by lingr7** [comment]
if set add local image file to inline, because now base64 in outlook2016 show not full.
