### ISSUE TITLE
Strange title with custom options and without name

### ISSUE THREAD

**Issue by nlamirault** [matcornic/hermes#6]
Hi,
Using custom options and without name, header of the text version of email is like that : 

```go
Body: hermes.Body{
	Greeting:  "Bonjour",
```

```
Bonjour ,,


```

HTML version seems correctly formatted.

**Comment by matcornic** [comment]
Use "Title" instead of greetings to override Greetings+Name

**Comment by nlamirault** [comment]
Thanks
